### ISSUE TITLE
Have you seen the Vessel project ?

### ISSUE THREAD

**Issue by xakraz** [shyiko/docker-vm#3]

**Comment by shyiko** [comment]
Hi. Yes. I have. It's a nice project and might be a good fit if you're on Mac OS X and don't really want to know how everything works "behind the scene". Things just work. 

docker-vm was built with "less is more" idea in mind. Meaning focus is on:
- simplicity. The only functional part of the whole project, Vagrantfile, is under 50 lines long. If you need a different OS, additional pre-installed/pre-configured tools, etc. - you just fork the project and modify Vagrantfile. If you tried Vagrant before (which nowadays I would say is quite probable)  - you already know how to use docker-vm. There are no docker-vm specific configurations, no UI to learn (which for me also means - less efforts to move the project forward and more time for documentation/bug reports).
- minimum abstraction. All you really need is `docker-vm up`. After that you just leverage existing tools just like you would on Linux. The experience you gain here is "transferrable" to any other OS.
- Mac OS X/Windows support out of box. You can use it on Linux but you obviously don't really need to.
